name: Hoardi
version: 1.0.0
main: de.hoarder.HoarderPlugin
api-version: '1.21'
description: Intelligent auto-sorting chest network with shelf previews
author: Marc Neuhaus
commands:
  hoardi:
    description: Manage the Hoardi chest network
    usage: /hoardi [setroot|sort|info|reload]
    aliases: [hr]
permissions:
  hoardi.admin:
    description: Allows managing the Hoardi plugin
    default: op
  hoardi.use:
    description: Allows creating preview shelves and using the network
    default: true
